### ISSUE TITLE
Plugin not initializing

### ISSUE THREAD

**Issue by ghost** [TBlueF/RottenFood#1]
This is the error in the console when server is starting and is trying to load the plugin. 

https://pastebin.com/6qUcFtHX

**Comment by TBlueF** [comment]
You used the Plugin-Version for **Sponge API 6.0** but you have **Sponge API 5.1** installed.

I uploaded a version of this plugin that should work with Sponge 5.1
https://github.com/TBlueF/RottenFood/releases/tag/v1.0-API-5.1
