### ISSUE TITLE
Add "age" for blocks in world

### ISSUE THREAD

**Issue by crymates** [TBlueF/RottenFood#2]
Could u pls add that u control specific blocks in the world ...
Let me explain:
You place 10 stone bricks in the world.
In config u told the plugin that an "stone_brick" lives 10 - 15 hours (in ticks).
After that 10 - 15 hours the stone_bricks will transform to "cracked stone brick" (not every stone brick at the same time, that's the thing).
In config u told the plugin that an "cracked_stone_brick" lives 50 - 100 hours (in ticks).
After that 50 - 100 hours the cracked_stone_bricks will transform to "air".

So the world in there u live is finite.
Every block can have an "end".
People has to work on their cities and repair them. U see who is offline for months and who's active :P
MAybe work together with some plugin like "PRISM" where it is detected when an block was placed and changed.

**Comment by crymates** [comment]
It's also possible to just give every block an player crafts an "age" automatically, so it's not needed to control the world blocks.

**Comment by crymates** [comment]
But finally it should affect the blocks in the world, not only in inventory.

**Comment by TBlueF** [comment]
Interesting idea, i will look into that

**Comment by crymates** [comment]
Love to hear that ;)

**Comment by TBlueF** [comment]
I fear i have to tell you that i wont implement this, for the following reasons:

To make the items age all the time, even if the player is not online or the chest is not loaded or even the server is offline, i store the age and the time of the last update on each item.
And then, when you open an inventory, i update every item in this inventory so it catches up with the current time..
If i want to recreate this feature on blocks that are placed in the world, i would need to update every block of every chunk when it is loaded.. and that is a really big number of updates..
Yes, i could store all blocks that a player placed and need to be updated in a list/database and just update those, but that'd lead to many problems with managing the data if the number of blocks gets bigger (big world/many players) or the config changes..
I also thought about random block-updates, but with those i would get far out of the scope of this plugin.
Additionally all those things would require a lot of programming-effort, and this plugin is sadly not my main project *(i have way too many "main"-projects i am working on already ^^')*

**Comment by TBlueF** [comment]
i have to admit tho that i really like the idea of a constantly decaying world.. **maybe** i'll find some time in the future and create a similar plugin..

**Comment by crymates** [comment]
Thx for ur explanation.

> maybe i'll find some time in the future and create a similar plugin..

That would be great mate, it's on of the best plugins of sponge then ;)
I really hope u find some time in near future, and just when it is an alpha release and not that stable, but just 

> Yes, i could store all blocks that a player placed and need to be updated in a list/database and just update those, but that'd lead to many problems with managing the data if the number of blocks gets bigger (big world/many players) or the config changes..

is one big point u should release an alpha unstable build of it, just testin, so "small" servers will work with it and if u got an good and strong database it will be great too.
Pls pls just do that and test it mate! ;)

Greetz,
Hannes

**Comment by crymates** [comment]
I would program it by myself if I had ur programming skills ;)
Do it for honor :P I will donate for this if desired.

**Comment by crymates** [comment]
I done it by myself :) Not an plugin, just scripting ^^
