### ISSUE TITLE
No Permissions

### ISSUE THREAD

**Issue by grimmdev** [TBlueF/RottenFood#3]
I added LuckPerms to my server and I was trying to setup permissions for it to work with any group, however there doesn't seem to be visible permissions anywhere.

**Comment by TBlueF** [comment]
@grimmdev What permissions are you missing?
Because there are no commands or anything that i thought would make sense to have permissions.

**Edit**: Everything should work like it is defined in the config, regardless of the permissions a player has.

**Comment by TBlueF** [comment]
Please reopen if you still have problems :)
