### ISSUE TITLE
Internal server errors & Console spam

### ISSUE THREAD

**Issue by Corcustos** [TBlueF/RottenFood#5]
I've recently re-added rotten food after uninstalling it, and my console is being spammed with [this](https://pastebin.com/uRJ1mmWa) and not letting people who had food in their inventory connect. Is there anything that can be done to resolve this, or have I screwed up my world for rottenfood?

It also caused some containers to clear themselves and nicknames to mix-match. Not sure if that's related but it only happened with rottenfood.

Versions:
RottenFood 1.1
Forge 2768
Sponge 3514
Nucleus 1.8.3

**Comment by TBlueF** [comment]
I was able to reproduce this, i think i fixed it with [Version 1.1.1](https://github.com/TBlueF/RottenFood/releases/tag/v1.1.1-API-7) (Commits: c65021b7a713f5efe05cdd8ad252370518ef7ea3 and ffe752b)
Please reopen this ticket if you are still experiencing this issue with the new version :)
