### ISSUE TITLE
[Request] add support for SpongeAPI ItemStacks for food items

### ISSUE THREAD

**Issue by PaxJaromeMalues** [TBlueF/RottenFood#6]
Hi Blue,

first of thank you for Rottenfood!
Lots of Modders apparently like to use datatypes to define their food items. Peobably because it is less of a hassle.
Sadly this leaves us with unclear item IDs like f.e. `<modname>:materials data: 225`.

I have two mods which will likely not be fixing their ID naming, but whichs items and functionality I still need on my server.

When it comes to Java coding I am fairly useless, so forking your mod and updating it is also not a possibility within a reasonable timeframe.

Currently your mod does support `ItemType` config entries like this:
```
items: [
	"minecraft:bread"
	"<modname>:alt_bread"
]
```

What I would like to request is, that like your `states` key, `items` does as well support addiontal data via ItemStack _probably_ like this

```
items: [
	{
		item: "natura:materials"
		data: "1"
		# equals an item called wheat_flour
	},
	{
		item: "natura:materials"
		data: "2"
		# equals an item called barley_flour
	}
]
```

This would be absolutely awesome!
Maybe I am also making a mistake here and you already did that.
Here is the error message I recieved:

```
[20:59:05] [Server thread/ERROR] [rottenfood]: Failed to load or create config-file!
ninja.leaping.configurate.objectmapping.ObjectMappingException: Input '{item=natura:materials, data=1}' was not a valid value for type org.spongepowered.api.item.ItemType
    at org.spongepowered.common.config.CatalogTypeTypeSerializer.deserialize(CatalogTypeTypeSerializer.java:49) ~[CatalogTypeTypeSerializer.class:1.12.2-2838-7.4.7]
    at org.spongepowered.common.config.CatalogTypeTypeSerializer.deserialize(CatalogTypeTypeSerializer.java:39) ~[CatalogTypeTypeSerializer.class:1.12.2-2838-7.4.7]
```

**Comment by TBlueF** [comment]
Hi @PaxJaromeMalues,

so .. unfortunately .. i don't really support this Plugin anymore.
With [BlueMap](https://bluemap.bluecolored.de/) being my main project (and another private one), i sadly don't really have any hobby-programming-time to spare :D

**However**, i gave myself 2h to see if i can implement this real-quick: [Version 1.3](https://github.com/TBlueF/RottenFood/releases/tag/v.1.3) is the result.
You should be able to do e.g. `natura:materials:2` now to get barley_flour to work separately from the other items :)

I have barely tested it, so i hope everything works as expected and this satisfies your (and a few other peoples) request. Try, and let me know! :)

**Comment by PaxJaromeMalues** [comment]
> Hi @PaxJaromeMalues,
> 
> so .. unfortunately .. i don't really support this Plugin anymore.
> With [BlueMap](https://bluemap.bluecolored.de/) being my main project (and another private one), i sadly don't really have any hobby-programming-time to spare :D
> 
> **However**, i gave myself 2h to see if i can implement this real-quick: [Version 1.3](https://github.com/TBlueF/RottenFood/releases/tag/v.1.3) is the result.
> You should be able to do e.g. `natura:materials:2` now to get barley_flour to work separately from the other items :)
> 
> I have barely tested it, so i hope everything works as expected and this satisfies your (and a few other peoples) request. Try, and let me know! :)

😯😯😯😯😯😯😯😯😯
Thank you so so much for your effort!
I will try it out today and let you know!
Thanks a bunch m8!
